services:
  web:
    build: .
    ports:
      - '3009:3000'
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - NEXT_BUILD_TIMEOUT=180000
    restart: unless-stopped
